namespace WSGClienteCM.Models
{
    public class AddressBindingModel
    {
        public string P_SIDDOC { get; set; }
        public string P_NIDDOC_TYPE { get; set; }
        public string P_CodAplicacion { get; set; }
        public string P_NUSERCODE { get; set; }
        public string P_SISRENIEC_IND { get; set; }
        public string P_NROW { get; set; }
        public string P_TipOper { get; set; }
        public string P_NRECOWNER { get; set; }
        public string P_ADDRESSTYPE { get; set; }
        public string P_DEFFECDATE { get; set; }
        public string P_SSTREET { get; set; }
        public string P_SZONE { get; set; }
        public string P_SCERTYPE { get; set; }
        public string P_SE_MAIL { get; set; }
        public string P_NLAT_SECOND { get; set; }
        public string P_NLON_SECOND { get; set; }
        public string P_NLAT_COORD { get; set; }
        public string P_NLON_COORD { get; set; }
        public string P_NCONTRAT { get; set; }
        public string P_NLAT_CARDIN { get; set; }
        public string P_NLAT_MINUTE { get; set; }
        public string P_NLON_CARDIN { get; set; }
        public string P_NLON_MINUTE { get; set; }
        public string P_NCERTIF { get; set; }
        public string P_NCLAIM { get; set; }
        public string P_NPOLICY { get; set; }
        public string P_NZIP_CODE { get; set; }
        public string P_NLAT_GRADE { get; set; }
        public string P_NCOUNTRY { get; set; }
        public string P_NLON_GRADE { get; set; }
        public string P_NBK_AGENCY { get; set; }
        public string P_NBANK_CODE { get; set; }
        public string P_NBRANCH { get; set; }
        public string P_NOFFICE { get; set; }
        public string P_NPROVINCE { get; set; }
        public string P_NPRODUCT { get; set; }
        public string P_NLOCAL { get; set; }
        public string P_SBUILD { get; set; }
        public string P_NMUNICIPALITY { get; set; }
        public string P_NFLOOR { get; set; }
        public string P_SDEPARTMENT { get; set; }
        public string P_SPOPULATION { get; set; }
        public string P_SINFOR { get; set; }
        public string P_SPOBOX { get; set; }
        public string P_SDESCADD { get; set; }
        public string P_NCOD_AGREE { get; set; }
        public string P_SREFERENCE { get; set; }
        public string P_STI_DIRE { get; set; }
        public string P_SNOM_DIRECCION { get; set; }
        public string P_SNUM_DIRECCION { get; set; }
        public string P_STI_BLOCKCHALET { get; set; }
        public string P_SBLOCKCHALET { get; set; }
        public string P_STI_INTERIOR { get; set; }
        public string P_SNUM_INTERIOR { get; set; }
        public string P_STI_CJHT { get; set; }
        public string P_SNOM_CJHT { get; set; }
        public string P_SETAPA { get; set; }
        public string P_SMANZANA { get; set; }
        public string P_SLOTE { get; set; }
        public string P_SREFERENCIA { get; set; }
        public string P_SCOD_DEP_UBI_DOM { get; set; }
        public string P_SCOD_PRO_UBI_DOM { get; set; }
        public string P_SCOD_DIS_UBI_DOM { get; set; }
        public string P_SDES_DEP_DOM { get; set; }
        public string P_SDES_PRO_DOM { get; set; }
        public string P_SDES_DIS_DOM { get; set; }
        public string P_SKEYADDRESS { get; set; }
        public string P_NUM_UPDATE { get; set; }
        public string p_NUM_INSERT { get; set; }
        public string P_SRECTYPE { get; set; }
    }
}
